Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -283,8 +283,9 @@ jobs:
           echo "🗑️ Deleted items: $DELETED" | tee -a $GITHUB_STEP_SUMMARY
           echo "✅ Passed items: $PASSED" | tee -a $GITHUB_STEP_SUMMARY
           EXITCODE=$((CHANGED + NEW + DELETED))
-          echo "EXITCODE=$EXITCODE" | tee -a $GITHUB_OUTPUT
-          ((EXITCODE > 0)) && echo -e "\n❌ Fail" || echo -e "\n✅ Pass" | tee -a $GITHUB_STEP_SUMMARY
+          echo | tee -a $GITHUB_STEP_SUMMARY
+          echo "EXITCODE=$EXITCODE" | tee -a $GITHUB_OUTPUT | tee -a $GITHUB_STEP_SUMMARY
+          ((EXITCODE > 0)) && echo -e "Fail ❌" || echo -e "Pass ✅" | tee -a $GITHUB_STEP_SUMMARY
           exit 0
 
       - name: 🆙 Upload artifact
